name: Linter

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '*.scss'
      - '*.js'
      - 'src/**/*.scss'
      - 'src/**/*.js'

jobs:
  run-linters:
    name: JS and SCSS
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          # Enable your linters here
          stylelint: true
          eslint: true
          prettier: false
